### ISSUE TITLE
Contributing in this project

### ISSUE THREAD

**Issue by aditirani** [ATLAS-Autoencoders-GSoC-2020-Closed/gsoc-assignment-Awshesh12#1]
Hello, I find this project interesting and want to contribute to this project. Please guide me on how to do that.

**Comment by caterina-doglioni** [comment]
Dear @aditirani,
this is not a valid repository for 2021 anymore. Please follow the timeline (https://hepsoftwarefoundation.org/activities/gsoc.html) and contact us again via email after March 9th. 
Caterina
